const nodemailer = require('nodemailer');

function createTransporter() {
  return nodemailer.createTransport({
    service: 'gmail',
    auth: {
      user: process.env.EMAIL_USER,
      pass: process.env.EMAIL_APP_PASSWORD,
    },
  });
}

async function sendMOMEmail({ to, meetingTitle, mom, date }) {
  const transporter = createTransporter();

  const actionItemsHTML = (mom.actionItems || [])
    .map((item) => {
      const check = item.status === 'completed' ? '&#9745;' : '&#9744;';
      const assignee = item.assignee ? ` <span style="color:#6b7280">(${item.assignee})</span>` : '';
      return `<li>${check} ${item.description}${assignee}</li>`;
    })
    .join('');

  const html = `
    <div style="font-family:'Segoe UI',system-ui,sans-serif;max-width:650px;margin:0 auto;color:#1e293b">
      <div style="background:linear-gradient(135deg,#3b82f6,#6366f1);padding:24px 30px;border-radius:12px 12px 0 0">
        <h1 style="color:white;margin:0;font-size:22px">Minutes of Meeting</h1>
        <p style="color:rgba(255,255,255,0.85);margin:6px 0 0;font-size:14px">${meetingTitle} &mdash; ${date}</p>
      </div>

      <div style="background:white;padding:24px 30px;border:1px solid #e2e8f0;border-top:none">
        <h2 style="font-size:16px;color:#334155;margin:0 0 8px">Summary</h2>
        <p style="color:#475569;line-height:1.6;margin:0 0 20px">${mom.summary}</p>

        ${mom.keyDiscussionPoints?.length ? `
          <h2 style="font-size:16px;color:#334155;margin:0 0 8px">Key Discussion Points</h2>
          <ul style="color:#475569;line-height:1.8;padding-left:20px;margin:0 0 20px">
            ${mom.keyDiscussionPoints.map((p) => `<li>${p}</li>`).join('')}
          </ul>
        ` : ''}

        ${mom.decisions?.length ? `
          <h2 style="font-size:16px;color:#334155;margin:0 0 8px">Decisions Made</h2>
          <ul style="color:#475569;line-height:1.8;padding-left:20px;margin:0 0 20px">
            ${mom.decisions.map((d) => `<li>${d}</li>`).join('')}
          </ul>
        ` : ''}

        ${mom.actionItems?.length ? `
          <h2 style="font-size:16px;color:#334155;margin:0 0 8px">Action Items</h2>
          <ul style="color:#475569;line-height:1.8;padding-left:20px;margin:0 0 20px;list-style:none">
            ${actionItemsHTML}
          </ul>
        ` : ''}

        ${mom.nextSteps?.length ? `
          <h2 style="font-size:16px;color:#334155;margin:0 0 8px">Next Steps</h2>
          <ul style="color:#475569;line-height:1.8;padding-left:20px;margin:0 0 20px">
            ${mom.nextSteps.map((s) => `<li>${s}</li>`).join('')}
          </ul>
        ` : ''}
      </div>

      <div style="background:#f8fafc;padding:16px 30px;border:1px solid #e2e8f0;border-top:none;border-radius:0 0 12px 12px;text-align:center">
        <p style="color:#94a3b8;font-size:12px;margin:0">Generated by MOM Generator</p>
      </div>
    </div>
  `;

  const result = await transporter.sendMail({
    from: `"MOM Generator" <${process.env.EMAIL_USER}>`,
    to: Array.isArray(to) ? to.join(', ') : to,
    subject: `MOM: ${meetingTitle} - ${date}`,
    html,
  });

  return result;
}

module.exports = { sendMOMEmail };
